# -*- coding: utf-8 -*-
"""retrieval_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Yp7NcUcEznz0tcRwOl3jOfneA5wov3J

Retrieval Agent for Indonesian Job Search
Collection name: indonesian_job_v2

This agent retrieves job information from Qdrant vector database
and will work as part of a multi-agent system orchestrated by supervisor.
"""

# INSTALL DEPENDENCIES

!pip install -qU langchain-community langchain-openai langchain-core
!pip install -qU langgraph langgraph-supervisor
!pip install -qU qdrant-client
!pip install -qU langchain-qdrant

# IMPORT LIBRARIES

from langchain_core.messages import SystemMessage, HumanMessage
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_qdrant import QdrantVectorStore
from langchain_core.tools import tool

from langgraph.prebuilt import create_react_agent
from langgraph_supervisor import create_supervisor

import getpass
import os
from google.colab import userdata
from qdrant_client import QdrantClient

# CREDENTIAL SETUP

# OpenAI API Key
if userdata.get('OPENAI_API_KEY'):
    os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')
else:
    os.environ["OPENAI_API_KEY"] = getpass.getpass("Enter API key for OpenAI : ")

# Qdrant credentials
if userdata.get('QDRANT_URL'):
    QDRANT_URL = userdata.get('QDRANT_URL')
else:
    QDRANT_URL = input("Enter Qdrant URL : ")

if userdata.get('QDRANT_API_KEY'):
    QDRANT_API_KEY = userdata.get('QDRANT_API_KEY')
else:
    QDRANT_API_KEY = getpass.getpass("Enter Qdrant API Key : ") or None

COLLECTION_NAME = "indonesian_job_v2"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# INITIALIZE QDRANT CLIENT AND VECTORSTORE
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# embeddings model
embeddings = OpenAIEmbeddings(
    model="text-embedding-3-small",
    openai_api_key=os.environ["OPENAI_API_KEY"]
)

# Qdrant client
qdrant_client = QdrantClient(
    url=QDRANT_URL,
    api_key=QDRANT_API_KEY,
    timeout=60 #mencegah request yang terlalu lama
)

# Verifying data collection
try:
    collection_info = qdrant_client.get_collection(COLLECTION_NAME)
    print(f"Connected to collection: {COLLECTION_NAME}")
    print(f"Total points: {collection_info.points_count}")
except Exception as e:
    print(f"Error connecting to collection: {e}")
    raise

# Initialize Qdrant vectorstore
vectorstore = QdrantVectorStore(
    client=qdrant_client,
    collection_name=COLLECTION_NAME,
    embedding=embeddings
)

# Create retriever
retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 5}
)

print("Qdrant vectorstore initialized successfully!")

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# CREATE RETRIEVAL TOOL
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

@tool
def search_indonesian_jobs(query: str) -> str:
    """
    Search and retrieve information about Indonesian job postings from the database.

    Use this tool to answer questions about:
    - Job positions and titles
    - Company names and information
    - Salary ranges and compensation
    - Job locations (cities/regions in Indonesia)
    - Work types (remote, on-site, hybrid)
    - Job qualifications and requirements
    - Job descriptions and responsibilities

    Args:
        query (str): The search query in Indonesian or English.
                    Examples: "data scientist Jakarta", "gaji software engineer",
                    "lowongan remote work"

    Returns:
        str: Formatted search results containing relevant job information
    """
    try:
        # Retrieve relevant documents using the retriever
        docs = retriever.invoke(query)

        if not docs:
            return "Maaf, tidak ditemukan informasi lowongan kerja yang relevan dengan pertanyaan Anda."

        # Format results
        results = []
        results.append(f"Ditemukan {len(docs)} lowongan kerja yang relevan:\n")

        for i, doc in enumerate(docs, 1):
            metadata = doc.metadata
            content = doc.page_content

            # Create structured output
            job_info = f"""
{'='*60}
Lowongan {i}:
{'='*60}
Posisi: {metadata.get('job_title', 'N/A')}
Perusahaan: {metadata.get('company_name', 'N/A')}
Lokasi: {metadata.get('location', 'N/A')}
Gaji: {metadata.get('salary', 'N/A')}
Tipe Kerja: {metadata.get('work_type', 'N/A')}

Deskripsi:
{content[:400]}{'...' if len(content) > 400 else ''}
"""
            results.append(job_info)

        return "\n".join(results)

    except Exception as e:
        error_msg = f"Terjadi kesalahan saat mencari data: {str(e)}"
        print(error_msg)
        import traceback
        traceback.print_exc()
        return error_msg

# Test the tool
print("Testing retrieval tool...")
test_result = search_indonesian_jobs.invoke("data scientist Jakarta")
if len(test_result) > 500:
  hasil = test_result = test_result[:500] + "..."
  print(hasil)
else :
  hasil = test_result
  print(hasil)

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# CREATE RETRIEVAL AGENT
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

retrieval_prompt='''
You are a professional Indonesian job search assistant specialized in helping users find relevant job opportunities in Indonesia.

YOUR PRIMARY OBJECTIVE:
Help users discover and understand job listings by retrieving accurate information from the job database.

MANDATORY INSTRUCTIONS:

1. TOOL USAGE (CRITICAL):
   - You MUST use the 'search_indonesian_jobs' tool for ANY job-related query
   - NEVER provide job information without using the tool first
   - Call the tool with specific, relevant search terms based on the user's question

2. RESPONSE LANGUAGE:
   - ALL responses MUST be in Bahasa Indonesia (Indonesian language)
   - Use polite and professional tone (formal Indonesian business language)
   - Maintain consistency in language throughout the conversation

3. INFORMATION ACCURACY:
   - Provide ONLY information retrieved from the tool results
   - Do NOT hallucinate or make up job listings, salaries, or company information
   - If the tool returns no results, acknowledge this clearly

4. HANDLING NO RESULTS:
   - If search returns empty or irrelevant results, suggest the user to:
     a) Use more specific keywords
     b) Try different job titles or synonyms
     c) Broaden the search criteria (e.g., remove location filters)

5. RESPONSE FORMATTING:
   - Structure answers in clear, scannable format
   - Use bullet points or numbered lists when presenting multiple jobs
   - Separate different job listings clearly
   - Highlight key information: job title, company, location, salary

6. SALARY QUERIES:
   - If salary information is available in tool results, provide it exactly as returned
   - If salary range exists, present both minimum and maximum values
   - If salary is not specified, state "Gaji tidak disebutkan" (Salary not specified)
   - NEVER estimate or guess salary figures

7. QUALIFICATION QUERIES:
   - Extract qualification requirements directly from job descriptions
   - Categorize into: education, experience, technical skills, soft skills
   - If qualifications are not clear, state what information is available

EXAMPLE QUERIES YOU CAN HANDLE:
- "Cari lowongan data scientist di Jakarta"
- "Berapa gaji rata-rata software engineer?"
- "Perusahaan apa saja yang buka lowongan remote?"
- "Apa kualifikasi untuk posisi product manager?"
- "Lowongan fresh graduate di Bandung"

WORKFLOW FOR EVERY USER QUERY:
Step 1: Identify the search intent (job title, location, company, etc.)
Step 2: Call search_indonesian_jobs tool with appropriate keywords
Step 3: Parse and analyze the tool results
Step 4: Format and present the information in clear Indonesian
Step 5: Offer to help with follow-up questions

CRITICAL RULE: Always search first, answer second. Never skip the tool usage.'''

# Create retrieval agent
job_retrieval_agent = create_react_agent(
    model="openai:gpt-4o-mini",
    tools=[search_indonesian_jobs],
    prompt=retrieval_prompt,
    name="job_retrieval_agent"
)

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# TEST RETRIEVAL AGENT
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

print("="*70)
print("TEST RETRIEVAL AGENT")
print("="*70 + "\n")

# Test with a sample query
test_query = "Cari lowongan data engineer di Jakarta dengan gaji tinggi"
print(f"Query: {test_query}\n")


print("Agent Response (Stream):\n")
for chunk in job_retrieval_agent.stream(
    {
        "messages": [
            {
                "role": "user",
                "content": test_query
            }
        ]
    }
):
    # Print each step
    agent_name = list(chunk.keys())[0]
    print(f"[{agent_name}]")

    if "messages" in chunk[agent_name]:
        for msg in chunk[agent_name]["messages"]:
            if hasattr(msg, 'content') and msg.content:
                print(f"  Content: {msg.content[:200]}...")
            if hasattr(msg, 'tool_calls') and msg.tool_calls:
                print(f"  Tool Calls: {[tc['name'] for tc in msg.tool_calls]}")
    print()

print("\n" + "="*70)
print("FINAL RESPONSE")
print("="*70 + "\n")

# Get final response
response = job_retrieval_agent.invoke(
    {
        "messages": [
            {
                "role": "user",
                "content": test_query
            }
        ]
    }
)

# Extract and display final answer
final_answer = response['messages'][-1].content
print(final_answer)

def ask_job_question(question: str, verbose: bool = True):
    """
    Helper function to query the job retrieval agent.

    Args:
        question (str): User's question in Indonesian
        verbose (bool): Print detailed execution steps

    Returns:
        str: Agent's response
    """
    if verbose :
        print(f"\n{'='*70}")
        print(f"Question: {question}")
        print(f"{'='*70}\n")

    response = job_retrieval_agent.invoke(
        {
            "messages": [
                {
                    "role": "user",
                    "content": question
                }
            ]
        }
    )

    answer = response['messages'][-1].content

    if verbose:
        print(f"Answer:\n{answer}")
        print(f"\n{'='*70}\n")

    return answer

"""# Test the Agent"""

user_query = [
    '''
looking for jobs that suitable for candidate with these skills :
- proficient in using Aspen Hysis, instrucalc, Matlab.
- experienced for creating process safety documents such as HAZOP, etc
- 5+ years experience as a chemical process engineer in petrochemical industry
- proficient in reading P&ID and PFD
- familiar with control method such as PID, MPC, etc
- familiar with field instrument integrating with sensors.

located in Jakarta and high salary (more than Rp.15.000.000) is highly prefered
    '''
]

answer = ask_job_question(user_query[0], verbose=True)

user_query = [
    '''
looking digital marketing specialist position Jakarta salary >15000000
SEO SEM social media ads content marketing analytics
Google Ads Meta Ads email marketing campaign optimization
experience 3-5+ years

    '''
]

answer = ask_job_question(user_query[0], verbose=True)